SimGNN:
    epochs: 10000
    patience: 50
    seed: 42
    start_val_iter: 100   # 设置第几代开始验证，减少验证时间消耗
    every_val_iter: 1     # 开始验证后，每隔几代进行一次验证
    gpu_index: 1          # 如果写-1，表示用cpu进行计算
    batch_size: 128
    lr: 0.001
    wandb: True           # 是否使用wandb联网记录训练结果

    histogram: True       # 是否使用直方图 所有人，除了官方，都不用直方图。我看了所有版本的SimGNN，无一例外都把直方图关了。因为加上以后这个性能是真的差。
    tensor_neurons: 16
    bins: 16
    filters_1: 64         # 第一层GCN的输出维度
    filters_2: 32         # 第二层GCN的输出维度
    filters_3: 16         # 第三层GCN的输出维度

    bottle_neck_neurons_1: 16
    bottle_neck_neurons_2: 8 
    bottle_neck_neurons_3: 4

    dropout: 0.5          # 论文中没有提及，但是官方TensorFlow代码中包含了dropout=0.5

AIDS700nef:
    num_features: 29

LINUX:
    num_features: 8

IMDBMulti:
    num_features: 89

ALKANE:
    num_features: 5